# Generated by Django 6.1.1 on 2026-09-14 00:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="popularity_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
